[tool.poetry]
name = "demo"
version = "0.1.0"
description = ""
authors = ["syuan0429 <syuan0429@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
